const $=s=>document.querySelector(s), canvas=$('#display'),ctx=canvas.getContext('2d');
const C={cream:'#fff4dd',paper:'#fffcf4',ink:'#25221d',muted:'#796f60',red:'#f56a48',yellow:'#ffdc69',green:'#b2cf9b',line:'#d8cbb4'};
const labels={upcoming:'未开始',open:'等待 Tibo',improvement:'产品改进',reset:'额度重置',both:'改进和重置',checking:'核实中',closed:'当日已结束'};
let state={page:0,detail:false,selected:0,scroll:0,offline:false,loading:true,setup:false,data:{status:null,challenge:null},errors:{},clockOffset:0};
const pad=n=>String(n).padStart(2,'0');
function clock(){return new Date(Date.now()+state.clockOffset)}
function parts(date,zone){return Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date).map(p=>[p.type,p.value]));}
function currentDay(){let c=state.data.challenge;if(!c)return 0;let p=parts(clock(),'America/Los_Angeles');return Math.max(0,Math.min(29,Math.floor((Date.parse(`${p.year}-${p.month}-${p.day}T00:00:00Z`)-Date.parse(c.start+'T00:00:00Z'))/86400000)+1));}
function stamp(iso){if(!iso)return '--';let p=parts(new Date(iso),'Asia/Shanghai');return `${p.month}/${p.day} ${p.hour}:${p.minute}`;}
function rect(x,y,w,h,fill,border=0,r=0){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(border){ctx.lineWidth=border;ctx.strokeStyle=C.ink;ctx.stroke();}}
function text(s,x,y,size=14,color=C.ink,weight=400,width){ctx.fillStyle=color;ctx.textBaseline='top';ctx.font=`${weight} ${size}px Passport, sans-serif`;if(width)ctx.fillText(s,x,y,width);else ctx.fillText(s,x,y);}
function lines(str,maxWidth){ctx.font='14px Passport,sans-serif';let result=[];for(const para of str.split('\n')){let row='';for(const ch of para){if(ctx.measureText(row+ch).width>maxWidth&&row){result.push(row);row=ch;}else row+=ch;}result.push(row);}return result;}
function header(){const stale=state.offline||Object.keys(state.errors).length>0;let status=state.setup?'配网预览':state.loading?'同步中':stale?'离线 / 缓存':'已同步';rect(20,18,5,5,stale?C.red:'#608457',0,3);text(status,31,10,14,C.muted);text('--%',186,10,14,C.muted);}
function footer(hint){const data=state.page?state.data.challenge:state.data.status;text(`更新 ${stamp(data?.fetchedAt)} CST`,16,270,12,C.muted);rect(14,291,212,1,C.line);ctx.textAlign='center';text(hint,120,297,12);ctx.textAlign='left';}
function drawHome(){let s=state.data.status;text('Codex Resets',14,39,20,C.ink,700);rect(14,74,212,133,C.paper,2,12);text('距最近一次额度重置',26,86,14,C.muted);let elapsed=s?Math.max(0,Math.floor((clock()-new Date(s.at))/1000)):0;text(s?String(Math.floor(elapsed/86400)):'--',25,109,48,C.red,750);text(s?`天 ${pad(Math.floor(elapsed/3600)%24)} 小时 ${pad(Math.floor(elapsed/60)%60)} 分`:'等待同步',26,161,14);text(s?`${stamp(s.at)} CST`:'--',26,184,12,C.muted);text('累计重置',16,216,14,C.muted);text('平均间隔 / 天',126,216,14,C.muted);text(s?String(s.total):'--',16,238,22,C.ink,700);text(s?Number(s.average).toFixed(1):'--',126,238,22,C.ink,700);footer('上下 切页  OK 公告');}
function drawAnnouncement(){let s=state.data.status;text('最近一次公告',14,42);rect(14,68,90,25,s?.type==='banked'?C.yellow:C.green,1,6);text(s?.type==='banked'?'备用重置':'常规重置',20,73,14);if(s?.scheduled)text('另有计划重置',114,72,12,C.red);rect(14,105,212,136,C.paper,1,8);let rows=lines(s?.text||'尚无公告，请先联网同步',190);state.scroll=Math.min(state.scroll,Math.max(0,rows.length-6));ctx.save();ctx.beginPath();ctx.rect(24,113,190,120);ctx.clip();rows.slice(state.scroll).forEach((l,i)=>text(l,24,113+i*19,14));ctx.restore();text('codex-resets.com',14,249,13,C.muted);footer('上下 滚动  OK 返回');}
function drawChallenge(){let c=state.data.challenge,day=currentDay();text('Tibo / 28',14,39,20,C.ink,700);text(day?pad(Math.min(day,28)):'--',14,66,40,C.red,700);text(day>28?'挑战已结束':day===0?'等待开始':'挑战日 / 28',94,71,14);let p=parts(clock(),'America/Los_Angeles');text(`${p.hour}:${p.minute} PT`,94,93,13,C.muted);for(let i=0;i<28;i++){let s=c?.days[i],selected=state.detail?state.selected===i:day===i+1;let fill=s==='improvement'?C.green:s==='reset'||s==='both'?C.red:s==='open'||s==='checking'?C.yellow:s==='closed'?C.line:C.paper;ctx.strokeStyle=selected?C.ink:C.line;rect(14+i%7*31,128+Math.floor(i/7)*29,26,24,fill,selected?2:0,5);if(!selected){ctx.lineWidth=1;ctx.strokeStyle=C.line;ctx.stroke();}ctx.textAlign='center';text(pad(i+1),27+i%7*31,132+Math.floor(i/7)*29,12);ctx.textAlign='left';}let selected=state.detail?state.selected:Math.max(0,Math.min(27,day-1));text(`第 ${pad(selected+1)} 天 · ${labels[c?.days[selected]]||'待确认'}`,14,248,14);footer(state.detail?'上下 选日  OK 返回':'上下 切页  OK 日历');}
function drawSetup(){text('连接 Wi-Fi · 预览',16,44,14);text('真机首次启动时',16,85,14,C.muted);text('屏幕显示专属热点和密码',16,110,14);text('手机连接后，浏览器打开',16,160,14,C.muted);text('192.168.4.1',16,192,22,C.red,700);text('此网页不会收集 Wi-Fi 密码',16,240,12,C.muted);text('长按上键 / Esc 关闭',26,296,12);}
function notes(){const s=state.data.status,c=state.data.challenge,day=currentDay(),selected=state.detail?state.selected+1:Math.max(1,Math.min(28,day));const n=$('#notes');n.replaceChildren();function el(tag,cls,content){let o=document.createElement(tag);o.className=cls;o.textContent=content;n.append(o);return o;}
 if(state.page===0){el('div','note-kicker','已经记录的好消息');let v=el('div','note-value',s?String(s.total):'—');let small=document.createElement('small');small.textContent='次额度重置';v.append(small);el('div','note-time',s?`LATEST · ${stamp(s.at)} CST`:'等待公开数据源');el('div','note-divider','');el('div','note-quote',s?`“${s.text.replace(/https?:\/\/\S+/g,'').trim()}”`:'下一次好消息，装进口袋。');el('div','note-author','@thsottiaux · 最新公告原文');}
 else{el('div','note-kicker','每天一项改进，或一次重置');let v=el('div','note-value',pad(selected));let small=document.createElement('small');small.textContent='/ 28 DAYS';v.append(small);el('div','note-status',labels[c?.days[selected-1]]||'等待同步');el('div','note-divider','');el('div','note-quote','一天一格。把每一个兑现的承诺，都留在这里。');el('div','note-author','按 OK 进入日历，用上下键逐日查看。');let legend=el('div','mini-legend','');for(const [cls,name]of [['','产品改进'],['red','额度重置']]){let span=document.createElement('span'),i=document.createElement('i');i.className=cls;span.append(i,document.createTextNode(name));legend.append(span);}}
}
function render(){ctx.setTransform(3,0,0,3,0,0);ctx.clearRect(0,0,240,320);rect(0,0,240,320,C.cream);header();if(state.setup)drawSetup();else if(state.page)drawChallenge();else if(state.detail)drawAnnouncement();else drawHome();document.querySelectorAll('[data-page]').forEach(b=>b.setAttribute('aria-selected',String(Number(b.dataset.page)===state.page)));$('#description-index').textContent=state.page?'02 / THE 28-DAY CHALLENGE':'01 / RESET TRACKER';$('#description-title').textContent=state.page?'一天一格，等一个兑现。':'等好消息，不用一直刷新。';$('#description-text').textContent=state.page?'跟着 Tibo 的美西时间，记录 28 天里每一次产品改进与额度重置。':'最近一次额度重置、累计次数和平均间隔，放进一块刚刚好的屏幕。';$('#source-link').href=state.page?'https://codex-resets.com/zh-CN/tibo-28':'https://codex-resets.com/zh-CN';const error=Object.keys(state.errors).length>0;$('#live-dot').classList.toggle('off',state.offline||error);$('#data-status').textContent=state.loading?'正在同步公开数据…':state.offline?'离线预览 · 显示上次同步数据':error?'部分数据更新失败 · 保留上次记录':'公开数据已同步 · 每 5 分钟更新';canvas.setAttribute('aria-label',state.setup?'Wi-Fi 配网预览':state.page?`28 天挑战，当前第 ${currentDay()} 天，选中第 ${state.detail?state.selected+1:Math.max(1,Math.min(28,currentDay()))} 天，${labels[state.data.challenge?.days[state.detail?state.selected:Math.max(0,Math.min(27,currentDay()-1))]]||'待确认'}`:`Codex 重置追踪，累计 ${state.data.status?.total??'未知'} 次，平均 ${state.data.status?.average??'未知'} 天`);notes();}
async function sync(force=false){if(state.offline)return;state.loading=true;render();try{let r=await fetch('/api/snapshot'+(force?'?refresh=1':''),{signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error('HTTP');let x=await r.json();state.data=x.data;state.errors=x.errors;state.clockOffset=Date.parse(x.serverNow)-Date.now();}catch{state.errors={status:'offline',challenge:'offline'};}finally{state.loading=false;render();}}
function key(which,long=false){if(long){if(which==='up'){state.setup=!state.setup;render();}else if(which==='ok')sync(true);return;}if(state.setup)return;if(which==='ok'){state.detail=!state.detail;state.scroll=0;if(state.page&&state.detail)state.selected=Math.max(0,Math.min(27,currentDay()-1));}else if(!state.detail){state.page=1-state.page;}else if(state.page){state.selected=(state.selected+(which==='down'?1:27))%28;}else{state.scroll=Math.max(0,state.scroll+(which==='down'?1:-1));}render();}
for(const which of ['up','down','ok']){let timer,long=false;const b=$('#key-'+which);b.addEventListener('pointerdown',e=>{if(e.button!==0)return;long=false;b.setPointerCapture(e.pointerId);b.classList.add('pressed');timer=setTimeout(()=>{long=true;key(which,true);},700);});b.addEventListener('pointerup',()=>{clearTimeout(timer);b.classList.remove('pressed');if(!long)key(which);});b.addEventListener('pointercancel',()=>{clearTimeout(timer);b.classList.remove('pressed');});b.addEventListener('click',e=>{if(e.detail===0)key(which);});}
for(const b of document.querySelectorAll('[data-page]'))b.addEventListener('click',()=>{state.page=Number(b.dataset.page);state.detail=false;state.setup=false;render();});
document.addEventListener('keydown',e=>{if(e.target.matches('input'))return;if(e.repeat)return;const k={ArrowUp:'up',ArrowDown:'down',Enter:'ok'}[e.key];if(k){e.preventDefault();key(k,e.shiftKey);}if(e.key==='Escape'){state.detail=false;state.setup=false;render();}});
$('#offline').addEventListener('change',e=>{state.offline=e.target.checked;render();if(!state.offline)sync();});$('#refresh').addEventListener('click',()=>sync(true));
render();document.fonts.ready.then(()=>{render();sync();});setInterval(()=>{if(!state.offline)sync();},300000);setInterval(render,60000);
